version: "1.0"
projectName: Kvv_1802_FedTestProject
runtimes:
- runtimeAlias: kvv_1802_FedTest
  assets:
  - name: fld_111399110_stage00.projects.fld72fcb003a7647dcb65a6751f32e6f4b.integrations:gvTest
    type: flow
    stepId: /0
    reference: fld_111399110_stage00.projects.fld72fcb003a7647dcb65a6751f32e6f4b.WmPackageServiceProvider.GB_1:readGlobalvariable
  - name: ertWorkflow
    type: workflow
    uid: fle6936120709a4a27971b16b030bbbaf5
    stepId: a1
    reference: services:add3Ints
  - name: ertWorkflow
    type: workflow
    uid: fle6936120709a4a27971b16b030bbbaf5
    stepId: a2
    reference: project.kvv_1802_fedtest.integrations:cache
  - name: ertWorkflow
    type: workflow
    uid: fle6936120709a4a27971b16b030bbbaf5
    stepId: a3
    reference: project.kvv_1802_fedtest.integrations:deepclonetest
  - name: ertWorkflow
    type: workflow
    uid: fle6936120709a4a27971b16b030bbbaf5
    stepId: a4
    reference: project.kvv_1802_fedtest.integrations:tppdaf
  - name: fld_111399110_stage00.projects.fld72fcb003a7647dcb65a6751f32e6f4b.integrations:tppdb
    type: flow
    stepId: /0
    reference: fld_111399110_stage00.projects.fld72fcb003a7647dcb65a6751f32e6f4b.WmPackageServiceProvider.SIQAJDBCAdapterTests.adapterServices:getData
  - name: restTest
    type: REST
    path: /tppert
    action: POST
    reference: fld_111399110_stage00.projects.fld72fcb003a7647dcb65a6751f32e6f4b.WmPackageServiceProvider.services:add3Ints
  - name: restTest
    type: REST
    path: /dafert
    action: POST
    reference: fld_111399110_stage00.projects.fld72fcb003a7647dcb65a6751f32e6f4b.WmPackageServiceProvider.project.kvv_1802_fedtest.integrations:tppdaf
- runtimeAlias: Cloud Designtime
  assets:
  - name: cdtWorkflow
    type: workflow
    uid: fleff785e7cb634c21ba466a734fe66952
    stepId: a1
    reference: services:add3Ints
  - name: cdtWorkflow
    type: workflow
    uid: fleff785e7cb634c21ba466a734fe66952
    stepId: a2
    reference: project.kvv_1802_fedtest.integrations:cache
  - name: cdtWorkflow
    type: workflow
    uid: fleff785e7cb634c21ba466a734fe66952
    stepId: a3
    reference: project.kvv_1802_fedtest.integrations:deepclonetest
  - name: cdtWorkflow
    type: workflow
    uid: fleff785e7cb634c21ba466a734fe66952
    stepId: a4
    reference: project.kvv_1802_fedtest.integrations:tppdaf
  - name: restTest
    type: REST
    path: /tpp
    action: POST
    reference: fld_111399110_stage00.projects.fld72fcb003a7647dcb65a6751f32e6f4b.WmPackageServiceProvider.services:add3Ints
  - name: restTest
    type: REST
    path: /daf
    action: POST
    reference: fld_111399110_stage00.projects.fld72fcb003a7647dcb65a6751f32e6f4b.WmPackageServiceProvider.project.kvv_1802_fedtest.integrations:cache
